import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import {chromium} from 'playwright';
import {createWorld,createGroup,relationship,restore} from '../dist/engine.mjs';
import {command} from '../dist/life.mjs';
const root=resolve('dist');
const server=createServer(async(req,res)=>{try{const url=req.url.split('?')[0].replace(/^\/garage-vivant(?=\/)/,''),path=resolve(root,'.'+(url==='/'?'/index.html':url));if(!path.startsWith(root+'/'))throw Error();const data=await readFile(path);res.setHeader('Content-Type',({'.html':'text/html','.mjs':'text/javascript','.js':'text/javascript','.css':'text/css','.json':'application/json'})[extname(path)]||'application/octet-stream');res.end(data);}catch{res.writeHead(404);res.end();}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}/garage-vivant/`;await mkdir('test-results',{recursive:true});const browser=await chromium.launch();const errors=[];
async function load(page,s){page.on('pageerror',e=>errors.push(e.stack));await page.addInitScript(save=>{if(!localStorage.getItem('garage-vivant-v1'))localStorage.setItem('garage-vivant-v1',JSON.stringify(save));},s);await page.goto(base);await page.waitForSelector('#profile .profile-head',{state:'attached',timeout:8000}).catch(e=>{console.log('PAGE ERRORS',errors);throw e;});}
async function capture(page,name){await page.screenshot({path:`test-results/${name}.png`,fullPage:false});}
const fixture=JSON.parse(await readFile(new URL('v04-world.json',import.meta.url)));
function world(){const s=createWorld(205,8);for(const a of s.people){a.needs.energy=95;for(const b of s.people)if(a!==b)Object.assign(relationship(s,a,b),{affinity:85,trust:85,tension:0});}const g=createGroup(s,s.people.slice(0,4).map(p=>p.id),{manual:true,name:'Les Cubes du Canal'});g.development=65;g.nextBookingAttempt=1e12;const song={genre:'Indie',emotion:'joy',tone:'lumineuse',intensity:40,resonance:60,sources:[],hit:false,id:1,authors:[s.people[0].id],time:s.time,title:'Les néons du quartier',quality:65};s.songs=[song];s.nextSongId=2;g.repertoire=[{songId:1,mastery:70,rehearsals:4}];const npc=createGroup(s,s.people.slice(4,7).map(p=>p.id),{manual:true,name:'Les Voisins électriques'});npc.nextBookingAttempt=1e12;restore(s);return {s,g,npc};}
let page;try{
const {s,g,npc}=world();page=await browser.newPage({viewport:{width:1440,height:960}});await load(page,s);
assert.equal(await page.locator('#mini-calendar .season-slot').count(),4);
const header=await page.locator('header').boundingBox(),main=await page.locator('#main').boundingBox();assert(main.y>=header.y+header.height-1);
await page.locator('#people [data-person]').nth(7).click();await page.locator('#skills-edit summary').click();const slider=page.locator('[data-edit="skills:writing"]');await slider.scrollIntoViewIfNeeded();await slider.evaluate(el=>window.originalSlider=el);
for(const speed of [.5,1,10]){await page.locator('#speed').evaluate((el,value)=>{el.value=String(value);el.dispatchEvent(new Event('input',{bubbles:true}));},speed);await slider.focus();const before=await slider.boundingBox(),top=await page.locator('#inspector').evaluate(el=>el.scrollTop);await page.waitForTimeout(1100);assert(await slider.evaluate(el=>el===window.originalSlider&&document.activeElement===el));const after=await slider.boundingBox();assert(Math.abs(after.y-before.y)<3);// The scroll offset may compensate new content above; the focused editor must stay at its visual position.
}
const reading=await page.locator('#inspector').evaluate(el=>el.scrollTop);await page.locator('#people [data-person]').first().click();await page.locator('#people [data-person]').nth(7).click();assert(Math.abs((await page.locator('#inspector').evaluate(el=>el.scrollTop))-reading)<8);
await page.locator('#speed').evaluate(el=>{el.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true}));el.value='1.1';el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new PointerEvent('pointerup',{bubbles:true}));});assert.equal(await page.locator('#speed').inputValue(),'1');await page.locator('#speed').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#speed').inputValue(),'1.1');

await page.locator('#speed').fill('10');await page.waitForTimeout(300);await page.locator('#speed').fill('0');assert.equal(await page.locator('#speed-value').textContent(),'Pause');await page.locator('#speed-value').click();assert.equal(await page.locator('#speed-value').textContent(),'×1.0');await page.locator('#speed').fill('0');
await page.locator('#profile-wide').click();assert(await page.locator('#inspector').evaluate(e=>e.classList.contains('expanded')));
const module=page.locator('.profile-module').filter({has:page.locator('#needs')});await module.locator('[data-module-action="hide"]').click();assert(await page.locator('.hidden-modules #needs').count());await page.locator('[data-reset-layout]').click();
await page.locator('[data-bag-custom]').check();const weight=page.locator('[data-bag-weight$=":write"]');await weight.fill('35');await weight.press('Tab');await page.waitForTimeout(500);assert(Math.abs(Number(await weight.inputValue())-35)<.1);await capture(page,'v6-profile');
await page.locator('#profile-wide').click();await page.locator('[data-view="groups"]').click();await page.locator(`[data-group-select="${npc.id}"]`).click();assert((await page.locator('.band-detail h2').textContent()).includes(npc.name));await page.locator('#band-search').fill('Voisins');assert.equal(await page.locator('.band-row').count(),1);await page.locator('#band-search').fill('');await capture(page,'v6-bands');
await page.locator('[data-view="shows"]').click();await page.locator('#show-group').selectOption(g.id);await page.locator('#show-slot').selectOption({label:'Tête d’affiche · 20 min'});await page.locator('[data-set-song="0"]').selectOption('1');await page.locator('#set-add').click();await page.locator('[data-set-song="1"]').selectOption('1');assert((await page.locator('.show-form').textContent()).includes('8/20'));
await page.locator('#preview-show').click();await page.waitForTimeout(2000);await page.locator('#show-pause').click();assert(await page.locator('.hero-card').isVisible());await page.locator('[data-stage-actor]').first().click();assert(await page.locator('#dialog').evaluate(e=>e.open));await page.locator('#dialog-close').click();await capture(page,'v6-show');await page.locator('#skip-show').click();assert(await page.locator('.show-result').isVisible());await page.locator('[data-return-preparation]').click();
let booked=false;for(let i=0;i<12&&!booked;i++){await page.locator('#book-show').click();booked=await page.locator('[data-advance-booking]').count()>0;}assert(booked);await page.locator('[data-advance-booking]').first().click();await page.waitForTimeout(500);assert(await page.locator('#performance-wrap').isVisible());const clock=await page.locator('#clock').textContent();await page.waitForTimeout(800);assert.equal(await page.locator('#clock').textContent(),clock);await page.reload();await page.waitForTimeout(500);assert(await page.locator('#performance-wrap').isVisible());assert.equal(await page.locator('#clock').textContent(),clock);await page.locator('#skip-show').click();assert(await page.locator('.show-result').isVisible());await page.locator('#replay-show').click();await page.locator('#skip-show').click();await page.locator('[data-return-preparation]').click();assert(await page.locator('.show-result').isVisible());await page.locator('#next-slot').click();await page.waitForTimeout(400);assert(await page.locator('#map-view').isVisible());await page.locator('#speed').fill('0');await page.locator('[data-view="groups"]').click();await page.locator(`[data-group-select="${g.id}"]`).click();assert((await page.locator('.band-detail').textContent()).includes('Les néons du quartier'));
await page.locator('#doc-search').click();await page.locator('#doc-query').fill('tension');await page.locator('#doc-results a').first().waitFor({state:'visible',timeout:8000});await page.locator('#dialog-close').click();
const popupPromise=page.waitForEvent('popup');await page.locator('#version').click();const popup=await popupPromise;await popup.waitForLoadState();assert(popup.url().includes('versions.html'));await popup.bringToFront();await popup.waitForSelector('#v060');await popup.waitForFunction(()=>JSON.parse(localStorage.getItem('garage-vivant-read-notes')||'[]').includes('v060'),{},{timeout:8000});await popup.close();
await page.locator('[data-view="journal"]').click();await page.locator('#main').evaluate(el=>el.scrollTop=300);await page.waitForTimeout(700);const journalTop=await page.locator('#main').evaluate(el=>el.scrollTop);await page.locator('[data-view="groups"]').click();await page.locator('[data-view="journal"]').click();assert(Math.abs((await page.locator('#main').evaluate(el=>el.scrollTop))-journalTop)<8);await page.locator('[data-view="relations"]').click();await page.locator('[data-pair]').first().click();assert(await page.locator('.selected-name').count()>=2);const relation=page.locator('[data-rel]').first();await relation.focus();await relation.evaluate(el=>window.originalRelation=el);await page.waitForTimeout(900);assert(await relation.evaluate(el=>el===window.originalRelation&&document.activeElement===el));await capture(page,'v6-relations');
await page.close();
page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await load(page,world().s);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.locator('#people [data-person]').first().click();await page.locator('#profile-wide').click();await page.locator('#inspector').evaluate(e=>e.scrollTop=500);const scroll=await page.locator('#inspector').evaluate(e=>e.scrollTop);await page.waitForTimeout(1200);assert(Math.abs((await page.locator('#inspector').evaluate(e=>e.scrollTop))-scroll)<3);await capture(page,'v6-mobile-profile');await page.locator('#close-inspector').click();await page.locator('[data-view="shows"]').click();await capture(page,'v6-mobile-calendar');
assert.deepEqual(errors,[]);console.log('V6 Chromium passed: modular profiles, Rapin editing, compact bands, multiple songs, real booking, live clock freeze, skip, history, docs search, patch tab, matrix and mobile scroll.');
}catch(e){if(page)await capture(page,'failure');throw e;}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
