import {skipShow,nextSlot} from '../dist/life.mjs';
import assert from 'node:assert/strict';
import {createWorld,step,scenario,restore,addPerson,removePerson,chemistry,NEEDS,SKILLS,PLACES,relationship} from '../dist/engine.mjs';
let a=createWorld(2040),b=createWorld(2040);step(a,1440*7);step(b,1440*7);assert.deepEqual(a,b,'Seed and steps must be reproducible');assert(a.songs.length>0,'Music must produce songs');assert(Object.values(a.rels).some(r=>r.meetings>0),'People must meet');
for(let seed=1;seed<=8;seed++){let s=createWorld(seed,seed===8?24:8);for(let day=0;day<4;day++){step(s,1440);if(s.performance?.status==='playing'){skipShow(s,true);nextSlot(s);}for(const p of s.people){assert(Number.isFinite(p.x)&&Number.isFinite(p.y));assert(p.x>=0&&p.x<=1100&&p.y>=0&&p.y<=670);for(const v of [...Object.values(p.needs),...Object.values(p.skills)])assert(Number.isFinite(v)&&v>=0&&v<=100);if(p.action){assert(PLACES.some(x=>x.id===p.action.dest));assert(p.action.remaining>0);}else assert(p.engagement||p.waitUntil>=s.time||s.events.some(e=>e.time===s.time&&e.text.startsWith(p.name+' se réveille')));assert(p.memories.length<=6);}for(const r of Object.values(s.rels)){assert(r.affinity>=-100&&r.affinity<=100);assert(r.trust>=0&&r.trust<=100);assert(r.tension>=0&&r.tension<=100);}}
assert.deepEqual(restore(JSON.parse(JSON.stringify(s))),s);}
let jam=createWorld(77);scenario(jam,'Soirée jam');step(jam,160);assert(jam.events.some(e=>e.type==='music'&&e.ids.length===2),'Jam scenario must lead to joint playing');let t=createWorld(44);scenario(t,'Tensions');step(t,240);assert(t.events.some(e=>e.type==='conflict'),'Tension scenario must create conflicts');
let s=createWorld(),p=s.people[0],q=s.people[1];assert.equal(chemistry(p,q),chemistry(q,p));relationship(s,p,q).affinity=50;assert.notEqual(relationship(s,q,p).affinity,50,'Relationships must be directed');step(s,80);let exported=restore(JSON.parse(JSON.stringify(s)));step(s,400);step(exported,400);assert.deepEqual(s,exported,'Import must continue the exact simulation');let added=addPerson(s);removePerson(s,added.id);assert(!Object.keys(s.rels).some(k=>k.split('>').includes(added.id)));
assert.throws(()=>restore({version:'bad'}));let corrupt=JSON.parse(JSON.stringify(s));corrupt.people[0].needs.energy='x';assert.throws(()=>restore(corrupt));
console.log(JSON.stringify({passed:true,deterministic:true,simulatedDays:39,songs:a.songs.length,interactions:Object.values(a.rels).reduce((x,r)=>x+r.meetings,0),population24:true}));
