import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {VERSION,ACTIONS,NEEDS,EMOTIONS,createWorld,step,restore,scenario,decide,scores,relationship,advance,support,conflictRisk,dominantEmotion,createGroup,groupsOf,formationPlan,formationEligible,refreshReputation,liveSessions,removePerson,compositionProject,interaction} from '../dist/engine.mjs';
const copy=x=>JSON.parse(JSON.stringify(x));
for(const v of ['v01','v02']){const legacy=JSON.parse(readFileSync(new URL(`./${v}-world.json`,import.meta.url),'utf8')),world=restore(legacy);assert.equal(world.version,VERSION);assert.equal(world.time,legacy.time);assert.equal(world.people[0].name,legacy.people[0].name);assert.equal(world.people[0].needs.energy,legacy.people[0].needs.energy);assert.equal(world.rels['p1>p2'].affinity,legacy.rels['p1>p2'].affinity);assert.equal(world.songs.length,legacy.songs.length);assert(!('food' in world.people[0].needs));assert(!('money' in world.people[0]));assert(world.groups.length===1);assert(world.people.every(p=>p.countsSince===legacy.time));step(world,600);restore(world);}
assert.deepEqual(Object.keys(ACTIONS).filter(k=>!ACTIONS[k].internal),['relax','social','practice','jam','write','decadence']);assert(!NEEDS.food&&!NEEDS.comfort);
// Needs, traits and old priorities do not reweight the finite bag.
const choice=createWorld(91),chooser=choice.people[0],before=scores(choice,chooser);chooser.needs.energy=0;chooser.personality.creative=100;chooser.emotions.distress=100;chooser.priorities.write=0;assert.deepEqual(scores(choice,chooser),before);decide(choice,chooser);assert.notEqual(chooser.action.key,'sleep');
// Each completed writing session advances a persistent artifact; finishing a song takes several sessions.
const writing=createWorld(7,2),writer=writing.people[0];for(const p of writing.people){decide(writing,p,'relax');p.action.remaining=100000;p.sleep.nextBedtime=1e12;p.needs.energy=100;}writing.jams=[];writer.place='g1';writer.x=140;writer.y=236;decide(writing,writer,'write',{projectId:writer.draft.projectId});writer.actionRanges.write={min:75,max:75};while(writer.action.route.length)step(writing);const projectId=compositionProject(writing,writer).id;step(writing,90);assert.equal(writing.songs.filter(s=>s.authors.includes(writer.id)).length,0);assert.equal(writer.actionCounts.write.completed,1);assert.equal(compositionProject(writing,writer).id,projectId);assert(writer.songProgress>0&&writer.songProgress<100);
for(let session=0;session<15&&!writing.songs.some(x=>x.projectId===projectId);session++){writer.needs.energy=100;decide(writing,writer,'write',{projectId:writer.draft.projectId});writer.actionRanges.write={min:75,max:75};while(writer.action.route.length)step(writing);step(writing,90);}const completed=writing.songs.find(x=>x.projectId===projectId);assert(completed);assert.equal(writing.songs.filter(x=>x.projectId===projectId).length,1);assert(completed.quality>=0&&completed.quality<=100);assert(writing.projects.find(x=>x.id===projectId).sessions>=3);
// Solo jams play immediately; partners can join an existing session without resetting it.
const solo=createWorld(4,2),one=solo.people[0];decide(solo,one,'jam');one.action.route=[];one.place=one.action.dest;one.sleep.nextBedtime=1e12;step(solo,30);assert(one.actionCounts.jam.completed>0||one.action.elapsed>=30);
const jam=createWorld(20,2);for(const p of jam.people){p.needs.energy=100;p.sleep.nextBedtime=1e12;}decide(jam,jam.people[0],'jam');decide(jam,jam.people[1],'jam',{sessionId:jam.people[0].action.sessionId});for(const p of jam.people){p.action.route=[];p.place=p.action.dest;}step(jam);assert(liveSessions(jam).some(x=>x.participants.length===2));
// Group formation emerges from favorable encounters with reciprocal prerequisites; group membership is nonexclusive and uncapped.
const gr=createWorld(33,15);gr.jams=[];for(const p of gr.people){decide(gr,p,'relax');p.priorities.jam=0;p.priorities.form=0;p.place='g1';p.x=140;p.y=236;p.needs.energy=100;}
const [a,b]=gr.people;for(const r of [relationship(gr,a,b),relationship(gr,b,a)])Object.assign(r,{affinity:45,trust:30,collaboration:18,tension:0});a.priorities.form=1;assert(formationEligible(gr,a,b));assert(formationPlan(gr,a));decide(gr,a,'social');decide(gr,b,'social');for(let n=0;n<100&&!gr.groups.length;n++)interaction(gr,a,b,'discuss',true);assert(gr.groups.some(g=>g.members.includes(a.id)&&g.members.includes(b.id)));const large=createGroup(gr,gr.people.map(p=>p.id),{manual:true,name:'Quinze musiciens'});assert.equal(large.members.length,15);assert(groupsOf(gr,a).length>=2);createGroup(gr,[a.id,gr.people[2].id],{manual:true});assert(groupsOf(gr,a).length>=3);assert.equal(createGroup(gr,[a.id,gr.people[2].id],{manual:true}).id,gr.groups.at(-1).id,'No identical duplicate');removePerson(gr,b.id);restore(gr);
const natural=gr;assert(natural.groups.length>0,'Favorable eligible exchanges must form groups without a formation token');
// Reputation responds to the actual catalogue and talent, not a random free stat.
const rep=createWorld(19),p=rep.people[0];const initial=refreshReputation(rep,p).score;p.skills[p.instrument]=100;rep.songs.push({authors:[p.id],quality:90,resonance:95});assert(refreshReputation(rep,p).score>initial);
// The previous emotion and relationship loops remain effective.
const heart=createWorld(2040);scenario(heart,'Cœur brisé');step(heart,180);const project=compositionProject(heart,heart.people[0]);assert(project);assert.equal(project.emotion,'distress');assert(project.sources.some(x=>x.text.includes('avance')||x.text.includes('refus')));
const su=createWorld(8),[target,helper]=su.people;target.emotions.distress=80;helper.personality.kind=95;let trust=relationship(su,target,helper).trust,success=false;for(let n=0;n<100&&!success;n++){trust=relationship(su,target,helper).trust;success=support(su,helper,target)>0;}assert(success);assert(relationship(su,target,helper).trust>trust);
const ro=createWorld(99),[r1,r2]=ro.people;relationship(ro,r1,r2).love=10;Object.assign(relationship(ro,r2,r1),{affinity:-100,tension:100});let rejected;for(let n=0;n<100&&!rejected;n++){const result=advance(ro,r1,r2);if(!result.accepted)rejected=result;else ro.time+=721;}assert(rejected);assert(r1.emotions.distress>0);assert.equal(rejected.event.rolls.result,null);assert.equal(advance(ro,r1,r2),null);
// Save/restore preserves all songs (including more than 100) and exact future behavior.
const long=createWorld(24);long.decisionMode='bag';step(long,1440*6);assert(long.songs.length>0);const historical=copy(long.songs[0]);for(let i=0;i<120;i++)long.songs.push({...copy(historical),id:long.nextSongId++,title:'Catalogue historique '+i,projectId:null});assert(long.songs.length>100);let cloned=restore(copy(long));step(long,400);step(cloned,400);assert.deepEqual(long,cloned);for(const person of long.people)for(const value of Object.values(person.emotions))assert(value>=0&&value<=100);
const broken=copy(long);broken.people[0].actionCounts.write.completed=-1;assert.throws(()=>restore(broken));
console.log(JSON.stringify({passed:true,migrations:['0.1','0.2'],write:'persistent project, multiple sessions, one final song',jams:'solo and collective playing',groups:natural.groups.length,largeGroup:15,fullCatalogue:long.songs.length,emotions:true,deterministic:true}));
