import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {VERSION,ACTIONS,NEEDS,EMOTIONS,createWorld,step,restore,scenario,decide,scores,relationship,advance,support,conflictRisk,dominantEmotion,createGroup,groupsOf,formationPlan,formationEligible,refreshReputation,liveSessions,removePerson,compositionProject} from '../dist/engine.mjs';
const copy=x=>JSON.parse(JSON.stringify(x));
for(const v of ['v01','v02']){const legacy=JSON.parse(readFileSync(new URL(`./${v}-world.json`,import.meta.url),'utf8')),world=restore(legacy);assert.equal(world.version,VERSION);assert.equal(world.time,legacy.time);assert.equal(world.people[0].name,legacy.people[0].name);assert.equal(world.people[0].needs.energy,legacy.people[0].needs.energy);assert.equal(world.rels['p1>p2'].affinity,legacy.rels['p1>p2'].affinity);assert.equal(world.songs.length,legacy.songs.length);assert(!('food' in world.people[0].needs));assert(!('money' in world.people[0]));assert(world.groups.length===1);assert(world.people.every(p=>p.countsSince===legacy.time));step(world,600);restore(world);}
assert.deepEqual(Object.keys(ACTIONS),['sleep','social','practice','jam','write','relax','form']);assert(!NEEDS.food);
for(const mode of ['utility','bag']){const s=createWorld(91);s.decisionMode=mode;const p=s.people[0];p.priorities.write=0;p.priorities.jam=0;p.personality.creative=100;p.emotions.sadness=100;for(let i=0;i<100;i++){decide(s,p);assert(!['write','jam'].includes(p.action.key));}p.needs.energy=3;p.priorities.sleep=0;decide(s,p);assert.equal(p.action.key,'sleep');}
// Each completed writing session advances a persistent artifact; finishing a song takes several sessions.
const writing=createWorld(7,2),writer=writing.people[0];for(const p of writing.people){p.action=null;p.priorities.jam=0;p.needs.energy=100;}writing.jams=[];writer.place='g1';writer.x=140;writer.y=236;decide(writing,writer,'write');while(writer.action.route.length)step(writing);const projectId=compositionProject(writing,writer).id;step(writing,75);assert.equal(writing.songs.filter(s=>s.authors.includes(writer.id)).length,0);assert.equal(writer.actionCounts.write.completed,1);assert.equal(compositionProject(writing,writer).id,projectId);assert(writer.songProgress>0&&writer.songProgress<100);
for(let session=0;session<6&&!writing.songs.some(x=>x.projectId===projectId);session++){writer.needs.energy=100;decide(writing,writer,'write');while(writer.action.route.length)step(writing);step(writing,75);}const completed=writing.songs.find(x=>x.projectId===projectId);assert(completed);assert.equal(writing.songs.filter(x=>x.projectId===projectId).length,1);assert(completed.quality>=0&&completed.quality<=100);assert(writing.projects.find(x=>x.id===projectId).sessions>=3);
// A jam without an available second musician never progresses as a joint activity.
const solo=createWorld(4,2);solo.jams=[];for(const p of solo.people){p.action=null;p.priorities.jam=0;p.needs.energy=100;}const one=solo.people[0];one.priorities.jam=2;decide(solo,one,'jam');while(one.action.route.length)step(solo);const loneId=one.action.sessionId;step(solo,30);assert.equal(solo.jams.find(x=>x.id===loneId).elapsed,0);assert.equal(one.action.elapsed,0);assert.equal(liveSessions(solo).filter(x=>x.type==='jam').length,0);step(solo,60);assert.equal(one.actionCounts.jam.completed,0);assert.equal(one.action.key,'practice');
// Two people receive the same destination; the clock only starts once both have arrived.
const jam=createWorld(20,2);jam.jams=[];for(const p of jam.people){p.action=null;p.needs.energy=100;p.emotions.anger=0;}decide(jam,jam.people[0],'jam');assert.equal(jam.people[0].action.sessionId,jam.people[1].action.sessionId);assert.equal(jam.people[0].action.dest,jam.people[1].action.dest);const sid=jam.people[0].action.sessionId;while(jam.people.some(p=>p.action.route.length))step(jam);assert(liveSessions(jam).some(x=>x.participants.length===2));for(let i=0;i<120&&!jam.people.every(p=>p.actionCounts.jam.completed>0);i++)step(jam);assert(jam.people.every(p=>p.actionCounts.jam.completed===1));
// Group formation is an autonomous action with reciprocal prerequisites; group membership is nonexclusive and uncapped.
const gr=createWorld(33,15);gr.jams=[];for(const p of gr.people){p.action=null;p.priorities.jam=0;p.priorities.form=0;p.place='g1';p.x=140;p.y=236;p.needs.energy=100;}
const [a,b]=gr.people;for(const r of [relationship(gr,a,b),relationship(gr,b,a)])Object.assign(r,{affinity:45,trust:30,collaboration:18,tension:0});a.priorities.form=1;assert(formationEligible(gr,a,b));assert(formationPlan(gr,a));decide(gr,a,'form');decide(gr,b,'write');b.action.dest='g1';b.action.route=[];while(a.action?.key==='form'&&a.action.route.length)step(gr);step(gr,20);assert(gr.groups.some(g=>g.members.includes(a.id)&&g.members.includes(b.id)));const large=createGroup(gr,gr.people.map(p=>p.id),{manual:true,name:'Quinze musiciens'});assert.equal(large.members.length,15);assert(groupsOf(gr,a).length>=2);createGroup(gr,[a.id,gr.people[2].id],{manual:true});assert(groupsOf(gr,a).length>=3);assert.equal(createGroup(gr,[a.id,gr.people[2].id],{manual:true}).id,gr.groups.at(-1).id,'No identical duplicate');removePerson(gr,b.id);restore(gr);
const natural=createWorld(2040);step(natural,4320);assert(natural.groups.length>0,'Natural relationships should form groups');
// Reputation responds to the actual catalogue and talent, not a random free stat.
const rep=createWorld(19),p=rep.people[0];const initial=refreshReputation(rep,p).score;p.skills[p.instrument]=100;rep.songs.push({authors:[p.id],quality:90,resonance:95});assert(refreshReputation(rep,p).score>initial);
// The previous emotion and relationship loops remain effective.
const heart=createWorld(2040);scenario(heart,'Cœur brisé');step(heart,180);const project=compositionProject(heart,heart.people[0]);assert(project);assert.equal(project.emotion,'sadness');assert(project.sources.some(x=>x.text.includes('décline les avances')));
const su=createWorld(8),[target,helper]=su.people;Object.assign(target.emotions,{anger:80,sadness:75,fear:45});helper.personality.kind=95;helper.emotions.anger=0;let risk=conflictRisk(su,target,helper),trust=relationship(su,target,helper).trust;assert(support(su,helper,target)>0);assert(conflictRisk(su,target,helper)<risk);assert(relationship(su,target,helper).trust>trust);
const ro=createWorld(99),[r1,r2]=ro.people;Object.assign(relationship(ro,r1,r2),{attraction:95,affinity:50});relationship(ro,r2,r1).attraction=10;assert.equal(advance(ro,r1,r2).accepted,false);assert(r1.emotions.sadness>20);assert.equal(advance(ro,r1,r2),null);ro.time+=721;Object.assign(relationship(ro,r2,r1),{attraction:80,affinity:50});assert(advance(ro,r1,r2).accepted);
// Save/restore preserves all songs (including more than 100) and exact future behavior.
const long=createWorld(24);long.decisionMode='bag';step(long,1440*6);assert(long.songs.length>0);const historical=copy(long.songs[0]);for(let i=0;i<120;i++)long.songs.push({...copy(historical),id:long.nextSongId++,title:'Catalogue historique '+i,projectId:null});assert(long.songs.length>100);let cloned=restore(copy(long));step(long,400);step(cloned,400);assert.deepEqual(long,cloned);for(const person of long.people)for(const value of Object.values(person.emotions))assert(value>=0&&value<=100);
const broken=copy(long);broken.people[0].actionCounts.write.completed=-1;assert.throws(()=>restore(broken));
console.log(JSON.stringify({passed:true,migrations:['0.1','0.2'],write:'persistent project, multiple sessions, one final song',jams:'require two present musicians',groups:natural.groups.length,largeGroup:15,fullCatalogue:long.songs.length,emotions:true,deterministic:true}));
