import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createWorld,step,restore,decide,relationship,chemistryKnowledge,compositionProject,journalEntries,musicalOutcome,MUSIC_OUTCOMES,scenario,refreshReputation,removePerson} from '../dist/engine.mjs';
const copy=x=>JSON.parse(JSON.stringify(x));
function quiet(seed=77,count=2){const s=createWorld(seed,count);for(const p of s.people){for(const k in p.priorities)p.priorities[k]=0;p.priorities.sleep=2;p.needs.energy=100;decide(s,p,'sleep');}return s;}
function writeSession(s,p){p.needs.energy=100;decide(s,p,'write');const count=p.actionCounts.write.completed;for(let n=0;n<220&&p.actionCounts.write.completed===count;n++)step(s);assert.equal(p.actionCounts.write.completed,count+1);}
// Current worlds migrate without discarding history, counters, groups or ongoing appointments.
for(const file of ['v03-world.json','v03-active-world.json']){const previous=JSON.parse(readFileSync(new URL(file,import.meta.url))),s=restore(previous);assert.deepEqual(s.songs,previous.songs);assert.deepEqual(s.groups.map(g=>Object.fromEntries(Object.keys(previous.groups.find(old=>old.id===g.id)).map(key=>[key,g[key]]))),previous.groups);assert.equal(s.time,previous.time);for(let i=0;i<s.people.length;i++){assert.deepEqual(s.people[i].actionCounts,previous.people[i].actionCounts);assert.deepEqual(s.people[i].needs,previous.people[i].needs);assert.equal(s.people[i].action?.key,previous.people[i].action?.key);assert.equal(s.people[i].action?.sessionId,previous.people[i].action?.sessionId);}assert(s.activities.length);const cloned=restore(copy(s));step(s,300);step(cloned,300);assert.deepEqual(s,cloned);}
// Interrupted writing retains its project and creative phase; polishing cannot wash out its origins.
const s=quiet(),p=s.people[0];p.emotions.sadness=90;p.emotions.joy=0;decide(s,p,'write');while(p.action.route.length)step(s);step(s,30);const id=compositionProject(s,p).id,progress=p.songProgress;decide(s,p,'relax');assert.equal(compositionProject(s,p).id,id);assert.equal(p.songProgress,progress);assert.equal(p.actionCounts.write.interrupted,1);let resumed=restore(copy(s));for(let n=0;n<8&&!resumed.songs.some(x=>x.projectId===id);n++){const author=resumed.people[0];if(n>0){author.emotions.sadness=0;author.emotions.joy=100;}writeSession(resumed,author);}const song=resumed.songs.find(x=>x.projectId===id);assert(song);assert.equal(song.emotion,'sadness');assert.equal(resumed.songs.filter(x=>x.projectId===id).length,1);assert(resumed.projects.find(x=>x.id===id).sessions>=3);
// All six outcomes exist and apply different effects; repeated identical moments diminish within a session.
const seen=new Set();for(let seed=1;seed<180;seed++){const x=quiet(seed),[a,b]=x.people;const j={id:'test',outcomes:{}};a.personality.kind=90;b.personality.kind=90;a.skills[a.instrument]=90;b.skills[b.instrument]=10;a.genre='Jazz';b.genre='Punk';const oldSkill=b.skills[b.instrument],oldTrust=relationship(x,b,a).trust;const event=musicalOutcome(x,a,b,j);seen.add(event.outcome);assert(MUSIC_OUTCOMES[event.outcome]);assert(event.effects&&event.explanation);if(event.outcome==='learn'){assert(b.skills[b.instrument]>oldSkill);assert(relationship(x,b,a).trust>oldTrust);}if(event.outcome==='debate')assert(relationship(x,b,a).tension>0);if(event.outcome==='clash')assert(relationship(x,b,a).trust<oldTrust||x.events.some(e=>e.type==='support'));const state=copy(x);journalEntries(x);assert.deepEqual(x,state,'Rendering journal must not reapply effects');}assert.equal(seen.size,6);
const repeated=quiet(2),[ra,rb]=repeated.people,repeatSession={id:'repeat',outcomes:Object.fromEntries(Object.keys(MUSIC_OUTCOMES).map(k=>[k,3]))};assert(musicalOutcome(repeated,ra,rb,repeatSession).repeatFactor<1);
// An idea is carried into the next project, once per author, with provenance.
const ideas=quiet(55),[ia,ib]=ideas.people;const ideaSession={id:'ideas',outcomes:{}};let idea;for(let n=0;n<80&&!idea;n++){const e=musicalOutcome(ideas,ia,ib,ideaSession);if(e.outcome==='idea')idea=e;}assert(idea);ideas.activities.push({id:'ideas',key:'jam',time:ideas.time,end:ideas.time,status:'completed',activeMinutes:85,place:'g1',ids:[ia.id,ib.id],events:[idea]});ia.draft.projectId=null;ia.draft.samples=0;ia.draft.sources=[];decide(ideas,ia,'write');assert(compositionProject(ideas,ia).sources.some(x=>x.id===idea.id));
// Knowledge comes from distinct completed common sessions, never from reading or repeated moments.
const jam=quiet(204),[a,b]=jam.people;a.priorities.jam=2;b.priorities.jam=2;decide(jam,b,'practice');assert.equal(chemistryKnowledge(jam,a,b).grade,'?');decide(jam,a,'jam');const sid=a.action.sessionId;assert.equal(b.action.sessionId,sid);while(jam.people.some(p=>p.action.route.length))step(jam);step(jam,20);assert.equal(chemistryKnowledge(jam,a,b).sessions,0);let clones=restore(copy(jam));for(let n=0;n<120&&a.actionCounts.jam.completed===0;n++)step(jam);for(let n=0;n<120&&clones.people[0].actionCounts.jam.completed===0;n++)step(clones);assert.deepEqual(jam,clones);assert.equal(chemistryKnowledge(jam,a,b).sessions,1);assert.equal(chemistryKnowledge(jam,b,a).sessions,1);const rows=journalEntries(jam,{filter:'jam'});assert.equal(rows.filter(x=>x.id===sid).length,1);assert(rows.find(x=>x.id===sid).events.some(x=>x.outcome));assert.equal(rows.find(x=>x.id===sid).activeMinutes,85);assert(journalEntries(jam,{filter:'selected',selected:b.id}).some(x=>x.id===sid));assert(journalEntries(jam,{raw:true,filter:'jam'}).length>1);
// Participant departures pause actual playing, retain everyone in the historical summary, and fall back to solo.
const departure=quiet(202),[da,db]=departure.people;da.priorities.jam=2;db.priorities.jam=2;decide(departure,db,'practice');decide(departure,da,'jam');while(departure.people.some(p=>p.action.route.length))step(departure);const departureId=da.action.sessionId;step(departure,15);const elapsed=departure.jams.find(j=>j.id===departureId).elapsed;decide(departure,db,'sleep');step(departure,20);assert.equal(departure.jams.find(j=>j.id===departureId).elapsed,elapsed);assert(journalEntries(departure,{filter:'selected',selected:db.id}).some(x=>x.id===departureId));step(departure,90);assert.equal(da.actionCounts.jam.completed,0);assert.equal(chemistryKnowledge(departure,da,db).sessions,0);
// Pace control changes output, and reputation is not earned by editing a draft.
const halted=quiet(9),hp=halted.people[0];halted.params.compositionPace=0;const reputation=refreshReputation(halted,hp).catalogue;writeSession(halted,hp);assert.equal(hp.songProgress,0);assert.equal(halted.songs.length,0);assert.equal(refreshReputation(halted,hp).catalogue,reputation);
const damaged=copy(resumed);damaged.projects[0].target=0;assert.throws(()=>restore(damaged));const missing=copy(resumed);delete missing.activities;assert.throws(()=>restore(missing));
const removed=quiet(888);const removedId=removed.people[0].action.activityId;removePerson(removed,removed.people[0].id);assert(removed.activities.find(x=>x.id===removedId).end!==null);restore(removed);
console.log(JSON.stringify({passed:true,migration:'V3 live jam + in-progress writing',outcomes:[...seen],projects:'persistent and emotion preserved',journal:'one row per session, read-only',chemistry:'distinct completed sessions',departures:true}));
