import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {createWorld,createGroup,restore,step,relationship,scores,decide,interact} from '../dist/engine.mjs';
import {command,skipShow,nextSlot,playTicks,advanceToBooking,availability,acceptance} from '../dist/life.mjs';
import {morale,selectBands,calendarMinute,pendingBooking,rollCalendar} from '../dist/calendar.mjs';
import {editBag,coolRelation,repairGrief} from '../dist/social.mjs';
const copy=x=>structuredClone(x);
for(const file of ['v051-active-world.json','v051-finished-world.json']){const old=JSON.parse(readFileSync(new URL(file,import.meta.url))),s=restore(old);assert.deepEqual(s.songs,old.songs);for(let i=0;i<s.people.length;i++){assert.deepEqual(s.people[i].skills,old.people[i].skills);assert.equal(s.people[i].actionCounts.sleep.completed,old.people[i].actionCounts.sleep.completed+old.people[i].actionCounts.relax.completed);}assert.equal(s.season.opportunities.length,4);if(s.performance.status==='playing'){const a=copy(s),b=restore(s);skipShow(a,true);for(let i=0;i<10000&&b.performance.status==='playing';i++)playTicks(b,1);assert.deepEqual(a.performance.result,b.performance.result);assert.equal(a.showHistory.length,1);restore(a);}else {assert.equal(s.performance.result.score,old.performance.result.score);const replay=copy(s);assert(command(replay,{type:'replay'}).ok);skipShow(replay);assert.deepEqual(replay.performance.result,old.performance.result);assert.equal(replay.showHistory.length,s.showHistory.length);}}
function prepared(count=8){const s=createWorld(39,count);for(const a of s.people){a.needs.energy=90;a.priorities.form=0;for(const b of s.people)if(a!==b)Object.assign(relationship(s,a,b),{affinity:95,trust:95,tension:0});}return s;}
const s=prepared(),bands=[];for(let i=0;i<4;i++){const g=createGroup(s,s.people.slice(i*2,i*2+2).map(p=>p.id),{manual:true});g.development=60;g.nextBookingAttempt=1e12;bands.push(g);}const big=s.season.opportunities[3];for(const g of bands){let r;for(let i=0;i<20&&!r?.ok;i++)r=command(s,{type:'book',actorId:g.members[0],groupId:g.id,opportunityId:big.id,setlist:[null],intention:'tight'});assert(r.ok);assert.equal(pendingBooking(s,g.id).status,'applied');assert(!command(s,{type:'book',actorId:g.members[0],groupId:g.id,opportunityId:s.season.opportunities[0].id,songId:null,intention:'tight'}).ok);}s.time=big.selectionAt;const twin=restore(s);selectBands(s,big);selectBands(twin,twin.season.opportunities[3]);assert.deepEqual(s,twin);assert.equal(s.bookings.filter(b=>b.status==='booked').length,3);assert.equal(s.bookings.filter(b=>b.status==='rejected').length,1);const loser=s.groups.find(g=>g.id===s.bookings.find(b=>b.status==='rejected').groupId);assert(morale(loser,s.time)<60);assert.equal(loser.reputation,0);const rng=s.rng;selectBands(s,big);assert.equal(s.rng,rng);assert.equal(morale(loser,s.time+2880),60);
const music=prepared(4),g=createGroup(music,music.people.slice(0,2).map(p=>p.id),{manual:true});g.development=70;g.nextBookingAttempt=1e12;const o=music.season.opportunities[0];let r;for(let i=0;i<20&&!r?.ok;i++)r=command(music,{type:'book',groupId:g.id,actorId:g.members[0],slotId:o.slots[1].id,opportunityId:o.id,setlist:[null,null],intention:'tight'});assert(r.ok);assert(advanceToBooking(music,r.bookingId).ok);const twinMusic=restore(music),clock=music.time;step(music,9999);assert.equal(music.time,clock);skipShow(music);for(let i=0;i<20000&&twinMusic.performance.status==='playing';i++)playTicks(twinMusic,1);assert.deepEqual(music.performance.result,twinMusic.performance.result);assert.equal(music.showHistory.length,1);assert.equal(music.showHistory[0].songs.length,2);const rep=g.reputation;skipShow(music);assert.equal(g.reputation,rep);nextSlot(music);restore(music);
const p=music.people[0];p.bag.custom=true;editBag(p,'write',35);assert(Math.abs(Object.values(p.bag.weights).reduce((a,b)=>a+b,0)-100)<1e-8);assert.equal(p.bag.weights.write,35);p.bag.locked=['write'];editBag(p,'practice',90);assert.equal(p.bag.weights.write,35);assert(p.bag.weights.practice<=65);p.needs.energy=1;assert.equal(scores(music,p).find(r=>r.key==='sleep').chance,100);restore(music);
const friend={affinity:90,tension:20,grief:{strength:0}},stranger={affinity:0,tension:20,grief:{strength:0}};for(let i=0;i<24;i++){coolRelation(music,friend);coolRelation(music,stranger);}assert(friend.tension<stranger.tension);const grudge={affinity:0,tension:2,grief:{strength:20}};coolRelation(music,grudge);assert(grudge.tension>2);repairGrief(grudge,10);assert(grudge.grief.strength<10);
const long=prepared();for(let i=0;i<100;i++){step(long,1440);if(long.performance?.status==='playing')skipShow(long,true);nextSlot(long);assert.equal(long.season.opportunities.length,4);assert(long.season.opportunities.every(o=>o.time>long.time));assert.equal(new Set([...long.eventArchive,...long.season.opportunities].map(o=>o.id)).size,long.eventArchive.length+4);restore(long);}assert(long.nextEventOrdinal>40);console.log('V6 passed: actual V5.1 migration, live freeze, multi-song skip determinism, unique engagement, weighted selection, morale recovery, editable bag, persistent tension, 100-day rolling calendar.');

// Two bands can share a musician in different slots of the same evening.
const shared=prepared(4),ga=createGroup(shared,shared.people.slice(0,2).map(p=>p.id),{manual:true}),gb=createGroup(shared,[shared.people[0].id,shared.people[2].id],{manual:true});for(const x of [ga,gb]){x.development=65;x.nextBookingAttempt=1e12;}const date=shared.season.opportunities[0];function reserve(band,slot){let result;for(let i=0;i<20&&!result?.ok;i++)result=command(shared,{type:'book',actorId:band.members[0],groupId:band.id,opportunityId:date.id,slotId:slot.id,songId:null,intention:'tight'});assert(result.ok);return result;}const bb=reserve(gb,date.slots[1]),ba=reserve(ga,date.slots[0]);assert(advanceToBooking(shared,ba.bookingId).ok);assert.equal(shared.performance.groupId,ga.id);skipShow(shared);assert(nextSlot(shared));skipShow(shared);assert.equal(shared.showHistory.length,2);assert(shared.showHistory.every(r=>r.members.includes(shared.people[0].id)));nextSlot(shared);restore(shared);
// An invalid modification keeps the previous engagement; a valid one replaces it atomically.
const changing=prepared(3),cg=createGroup(changing,changing.people.slice(0,2).map(p=>p.id),{manual:true});cg.nextBookingAttempt=1e12;const co=changing.season.opportunities[0];let cr;for(let i=0;i<20&&!cr?.ok;i++)cr=command(changing,{type:'book',actorId:cg.members[0],groupId:cg.id,opportunityId:co.id,slotId:co.slots[1].id,songId:null,intention:'tight'});assert(cr.ok);const original=copy(changing);assert(!command(changing,{type:'modifyBooking',bookingId:cr.bookingId,actorId:cg.members[0],setlist:[999],intention:'tight'}).ok);assert.deepEqual(changing,original);let modified;for(let i=0;i<20&&!modified?.ok;i++)modified=command(changing,{type:'modifyBooking',bookingId:cr.bookingId,actorId:cg.members[0],setlist:[null,null],intention:'emotional'});assert(modified.ok);assert.equal(changing.bookings.filter(b=>b.status==='booked').length,1);restore(changing);

// Replay keeps the exact collective morale used on stage, after it changes in the world.
const remembered=copy(music);assert(command(remembered,{type:'replay'}).ok);skipShow(remembered);assert.equal(remembered.performance.morale,music.performance.morale);assert.equal(remembered.showHistory.length,music.showHistory.length);

const emotional=prepared(2),eg=createGroup(emotional,emotional.people.map(p=>p.id),{manual:true});eg.stageMorale=27;assert(command(emotional,{type:'preview',actorId:eg.members[0],groupId:eg.id,songId:null}).ok);skipShow(emotional);const er=copy(emotional.performance.result);eg.stageMorale=90;assert(command(emotional,{type:'replay'}).ok);skipShow(emotional);assert.deepEqual(emotional.performance.result,er);
