import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {BAG_ACTIONS,BAG_SAMPLES,newBag,reserveToken,editTokens,emotionalMinute,updateTraits,effectiveTraits,interactionProbabilities,partnerWeight,coolRelationV7} from '../dist/v7.mjs';
import {createWorld,restore,step,decide,interaction,relationship,advanceSleeping,createGroup,addPerson,scores} from '../dist/engine.mjs';
import {command,skipShow,nextSlot} from '../dist/life.mjs';
import {emotionCompatible} from '../dist/stage.mjs';
import {exchangeTrace,catalogueHTML,rapinHTML} from '../dist/v7-view.mjs';
const copy=x=>structuredClone(x);
// A complete cycle delivers its multiset exactly once, even when values change.
for(let i=0;i<8;i++){const p={bag:newBag(i)},original=copy(p.bag.composition),counts=Object.fromEntries(BAG_ACTIONS.map(k=>[k,0]));for(let n=0;n<BAG_SAMPLES[i].reduce((a,b)=>a+b,0);n++){const key=reserveToken(p,()=>((n*37)%101)/101);counts[key]++;}assert.deepEqual(counts,original);assert.equal(p.bag.cycle,1);assert.equal(Object.values(p.bag.remaining).reduce((a,b)=>a+b,0),0);assert(editTokens(p,'write',99));reserveToken(p,()=>.999);assert.equal(p.bag.cycle,1);assert.equal(p.bag.composition.write,99);assert.equal(p.bag.reserved,null);assert(!editTokens(p,'sleep',10));assert(!editTokens(p,'write',1.5));}
const unchanged=createWorld(712,8);assert.deepEqual(unchanged.people.map(p=>Object.values(p.bag.composition).reduce((a,b)=>a+b,0)),[10,15,20,30,40,60,80,100]);const person=unchanged.people[0],rows=scores(unchanged,person);person.needs.energy=0;person.emotions.distress=100;person.personality.creative=100;person.priorities.write=0;assert.deepEqual(scores(unchanged,person),rows);
const refill=createWorld(88,2),re=refill.people[0];decide(refill,re,'relax');re.bag=newBag();for(const k of BAG_ACTIONS){re.bag.remaining[k]=0;re.bag.consumed[k]=re.bag.cycleComposition[k];}assert(rapinHTML(refill,re).includes('après remplissage'));decide(refill,re);assert.equal(re.bag.cycle,2);assert.equal(re.action.decision.reduce((n,r)=>n+r.chance,0),100);restore(refill);
// Personal pressure is continuous, replaces the lower tier and permits coexistence.
const pressure=createWorld(31,2).people[0];for(const k in pressure.needs)pressure.needs[k]=50;const threshold=pressure.needThresholds.energy;pressure.needs.energy=threshold.critical-1;pressure.needs.fun=100;pressure.emotions={distress:10,exaltation:10};emotionalMinute(pressure,{emotionDecay:0});assert.equal(pressure.emotions.distress,10+threshold.criticalRate);assert.equal(pressure.emotions.exaltation,10+pressure.needThresholds.fun.highRate);pressure.needs.energy=50;pressure.needs.fun=50;emotionalMinute(pressure,{emotionDecay:0});assert.equal(pressure.emotions.distress,10+threshold.criticalRate);emotionalMinute(pressure,{emotionDecay:1});assert(pressure.emotions.distress<10+threshold.criticalRate);
pressure.traits=['irritable'];pressure.emotionalThresholds=[{axis:'distress',threshold:25,trait:'irritable'},{axis:'exaltation',threshold:25,trait:'inspired'}];pressure.emotions={distress:25,exaltation:25};updateTraits(pressure);assert.deepEqual(pressure.activeTraits,['irritable','inspired']);pressure.emotions.distress=24.99;updateTraits(pressure);assert(!pressure.activeTraits.includes('irritable'));assert(effectiveTraits(pressure).includes('irritable'),'Permanent source survives conditional withdrawal');
// A failed search returns the token; it is neither a refusal nor completion.
const alone=createWorld(72,2),[seeker,busy]=alone.people;for(const p of alone.people){decide(alone,p,'practice');p.action.remaining=100000;p.sleep.nextBedtime=1e12;}seeker.bag=newBag();for(const field of ['composition','cycleComposition','remaining'])seeker.bag[field]={relax:0,social:1,practice:0,jam:0,write:0,decadence:0};decide(alone,seeker);seeker.action.route=[];seeker.place='park';step(alone,30);assert.equal(seeker.action,null);assert.equal(seeker.bag.remaining.social,0);assert.equal(seeker.bag.consumed.social,1);assert.equal(seeker.actionCounts.social.completed,0);assert(!alone.events.some(e=>e.outcome==='refused'));restore(alone);
// Starting a jam does not interrupt another intention; joining consumes at first play.
const music=createWorld(61,2),[host,joiner]=music.people;decide(music,joiner,'write');const held=copy(joiner.action);decide(music,host,'jam');assert.deepEqual(joiner.action,held);decide(music,joiner,'jam');for(const p of music.people){p.action.route=[];p.place=p.action.dest;}step(music);assert.equal(host.action.elapsed,1);assert.equal(joiner.action.elapsed,1);restore(music);
// Refusal uses only its acceptance roll; trace reports actual emotional reactions.
let refusal;for(let seed=1;seed<80&&!refusal;seed++){const s=createWorld(seed,2),[a,b]=s.people;Object.assign(relationship(s,b,a),{affinity:-100,tension:100});const e=interaction(s,a,b);if(!e.accepted){refusal={s,a,b,e};}}
assert(refusal);assert.equal(refusal.e.event.rolls.result,null);assert.equal(refusal.e.event.changes.after.b.relation.meetings,0);assert(refusal.e.event.changes.after.a.emotions.distress>refusal.e.event.changes.before.a.emotions.distress);assert(exchangeTrace(refusal.e.event).includes('non tiré après refus'));const stored=refusal.s.activities.flatMap(a=>a.events).find(e=>e.id===refusal.e.event.id);assert.deepEqual(stored.changes,refusal.e.event.changes);
const [a,b]=createWorld(9,2).people,r={affinity:-100,tension:100};a.emotions.distress=b.emotions.distress=100;const chances=interactionProbabilities(a,b,r);assert(chances.positive>0);assert(Math.abs(chances.positive+chances.neutral+chances.negative-1)<1e-10);
// Admission is logged once; admitted exchanges draw only their outcome.
const social=createWorld(15,3);for(const p of social.people){decide(social,p,'social');p.action.route=[];p.place='park';p.actionRanges.social={min:100,max:180};for(const q of social.people)if(p!==q)Object.assign(relationship(social,p,q),{affinity:80,trust:80,tension:0});}step(social,31);assert(social.events.some(e=>e.admission));assert(social.events.filter(e=>e.interaction).every(e=>e.rolls.acceptance===null));restore(social);
// Directed friendship and the actual development field weight partner selection.
const partners=createWorld(8,3),[one,two,three]=partners.people;const basic=partnerWeight(partners,one,two,relationship(partners,one,two)),band=createGroup(partners,[one.id,two.id],{manual:true});band.development=80;assert(partnerWeight(partners,one,two,relationship(partners,one,two))>basic+10);relationship(partners,one,three).affinity=75;assert(partnerWeight(partners,one,three,relationship(partners,one,three))>basic+6);
const friend={affinity:90,tension:40,grief:{strength:0}},stranger={affinity:0,tension:40,grief:{strength:0}};coolRelationV7(friend);coolRelationV7(stranger);assert(friend.tension<stranger.tension);assert(friend.affinity<90);
// Sleep uses no tokens and its shortcut runs the same minute simulation.
const sleep=createWorld(28,2);for(const p of sleep.people){p.sleep.required=480;p.sleep.habitual=240;p.needs.energy=15;decide(sleep,p,'sleep');p.action.route=[];p.place=p.home;}const bags=sleep.people.map(p=>copy(p.bag)),slow=copy(sleep);while(slow.people.every(p=>p.action?.key==='sleep'))step(slow);assert.equal(advanceSleeping(sleep),240);assert.deepEqual(sleep,slow);assert(sleep.people.every(p=>p.needs.energy===50));assert.deepEqual(sleep.people.map(p=>p.bag),bags);assert(sleep.people.every(p=>p.actionCounts.sleep.completed===1));
const guard=createWorld(7,2),sleeper=guard.people[0];decide(guard,sleeper,'sleep');const action=copy(sleeper.action);decide(guard,sleeper,'write');assert.deepEqual(sleeper.action,action);assert(!command(guard,{type:'action',actorId:sleeper.id,key:'write'}).ok);
const delayed=createWorld(55,2);delayed.time=1620;const late=delayed.people[0];late.sleep.bedtime=1380;late.sleep.nextBedtime=1380;step(delayed);assert.equal(late.action.key,'sleep');assert.equal(late.sleep.nextBedtime,2820,'A bedtime deferred past midnight must not skip the next night');
// Romantic eligibility and asymmetric progression do not force reciprocity.
const love=createWorld(3,2),[lover,target]=love.people;assert.equal(interaction(love,lover,target,'advance'),null);relationship(love,lover,target).love=5;Object.assign(relationship(love,target,lover),{affinity:100,tension:0});let positive;for(let n=0;n<100&&!positive;n++){const e=interaction(love,lover,target,'advance');if(e?.outcome==='favorable')positive=e;else love.time+=721;}assert(positive);assert.equal(relationship(love,target,lover).love,0);assert(relationship(love,lover,target).love>5);assert.equal(relationship(love,lover,target).couple,false);
const couples=createWorld(39,2);for(const p of couples.people){decide(couples,p,'relax');p.action.remaining=100000;p.sleep.nextBedtime=1e12;}const [ca,cb]=couples.people,ab=relationship(couples,ca,cb),ba=relationship(couples,cb,ca);ab.love=ba.love=50;for(let n=0;n<100&&!ab.couple;n++)step(couples,60);assert(ab.couple&&ba.couple);ba.love=20;for(let n=0;n<100&&ab.couple;n++)step(couples,60);assert(!ab.couple&&!ba.couple);restore(couples);
// Representative historical worlds preserve their music and current saves reject corruption.
for(const file of ['v01-world.json','v02-world.json','v03-active-world.json','v04-world.json','v051-active-world.json','v06-world.json']){const old=JSON.parse(readFileSync(new URL(file,import.meta.url))),s=restore(old);assert.equal(s.version,'0.7.1');assert.equal(s.songs.length,old.songs.length);if(old.version!=='0.1.0')assert.deepEqual(s.songs,old.songs);assert(s.people.every(p=>!('comfort' in p.needs)&&Object.keys(p.emotions).length===2));assert(Object.values(s.rels).every(r=>!('attraction' in r)));assert.deepEqual(restore(s),s);step(s,120);restore(s);}
const customized=JSON.parse(readFileSync(new URL('v06-world.json',import.meta.url)));customized.people[0].bag.custom=true;customized.people[0].bag.weights={sleep:10.2,social:20.2,practice:30.2,jam:20.2,write:19.2,form:0};const upgraded=restore(customized);assert.deepEqual(upgraded.people[0].bag.composition,{relax:10,social:20,practice:30,jam:20,write:19,decadence:0});assert.deepEqual(upgraded.people[0].legacyActionCounts.counts,customized.people[0].actionCounts);const damagedLegacy=copy(customized);damagedLegacy.people[0].emotions.joy='bad';assert.throws(()=>restore(damagedLegacy));
const clean=createWorld(104,8);step(clean,1440);const resumed=restore(clean);step(clean,1000);step(resumed,1000);assert.deepEqual(clean,resumed);for(const damage of [s=>s.people[0].bag.remaining.write++,s=>s.people[0].emotions.joy=10,s=>s.people[0].sleep.required='x',s=>s.people[0].activeTraits=['inspired'],s=>s.people[0].traits.push('alpha','beta')]){const bad=copy(clean);damage(bad);assert.throws(()=>restore(bad));}
assert(emotionCompatible('distress','sadness',7));assert(!emotionCompatible('distress','sadness',6));assert(emotionCompatible('joy','joy',6));assert(!emotionCompatible('exaltation','fear',7));
assert(catalogueHTML().includes('Solitaire'));assert(catalogueHTML().includes('débranché'));
console.log('V7 passed: finite cycles, pressures, source-preserving traits, failed searches, joinable sessions, refusal traces, partner weights, sleep equivalence, unreciprocated love, actual migration and exact continuation.');
