import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createWorld,step,restore,decide,createGroup,relationship,compositionProject,selectProject,interaction,proposeActivity,feel,log} from '../dist/engine.mjs';
import {newBag,editTokens,reserveToken,BAG_ACTIONS} from '../dist/v7.mjs';
import {musicName,normalizeName,plateauGain,classifySongs,V71_RULES} from '../dist/v71.mjs';
import {changeDecadence,command,skipShow,nextSlot} from '../dist/life.mjs';
import {activeDeck,createPerformance,advancePerformance,validatePerformance} from '../dist/stage.mjs';
import {catalogueEntries,DEFAULT_FILTERS,songDetailsHTML} from '../dist/catalogue.mjs';
function quiet(seed=61,n=2){const s=createWorld(seed,n);for(const p of s.people){p.sleep.nextBedtime=1e12;decide(s,p,'relax');p.action.remaining=100000;p.action.route=[];p.place='park';p.needs.energy=100;}return s;}
function bag(p,counts){p.bag=newBag();for(const k of BAG_ACTIONS){for(const f of ['composition','cycleComposition','remaining'])p.bag[f][k]=counts[k]||0;p.bag.consumed[k]=0;p.bag.pendingRemoval[k]=0;}}
// A requested removal cannot affect the undrawn bag, and never resurrects on refill.
const token={bag:newBag()};bag(token,{practice:2,relax:1});assert(editTokens(token,'practice',0));assert.equal(token.bag.remaining.practice,2);assert.equal(token.bag.pendingRemoval.practice,2);assert.equal(reserveToken(token,()=>.5),'practice');assert.equal(token.bag.remaining.practice,1);assert.equal(token.bag.consumed.practice,0);assert.equal(reserveToken(token,()=>.75),'practice');assert.equal(reserveToken(token,()=>0),'relax');assert.equal(reserveToken(token,()=>0),'relax');assert.equal(token.bag.remaining.practice,0);assert(editTokens(token,'write',3));assert.equal(token.bag.remaining.write,3);
// Interrupted and failed actions retain their consumed token.
const failed=quiet(),seeker=failed.people[0];bag(seeker,{social:1,practice:1});decide(failed,seeker);seeker.action.route=[];seeker.place='g1';step(failed,30);assert.equal(seeker.bag.remaining.social,0);assert.equal(seeker.bag.consumed.social,1);assert.equal(seeker.waitUntil,0);restore(failed);
// Solo Jam contributes expression immediately, but not repertoire mastery/coordination.
const jam=quiet(77),j=jam.people[0],g=createGroup(jam,jam.people.map(p=>p.id),{manual:true});g.repertoire=[{songId:1,mastery:20,rehearsals:0}];jam.songs=[{id:1,title:'Une chanson',authors:[j.id],genre:'Indie',quality:50,time:jam.time,intensity:10,emotion:'exaltation',tone:'exaltée',resonance:40,sources:[],hit:false}];const development=g.development;
decide(jam,j,'jam');j.action.route=[];j.place=j.action.dest;j.needs.expression=20;const session=jam.jams.find(x=>x.id===j.action.sessionId);step(jam,10);assert.equal(session.elapsed,10);assert(j.needs.expression>20);assert.equal(g.repertoire[0].mastery,20);assert.equal(g.development,development);
// Practice trains the selected instrument and piece, never expression by default.
const practice=quiet(95),p=practice.people[0];p.secondaryInstruments=['keys'];p.skills.keys=20;decide(practice,p,'practice',{songId:null});p.action.instrument='keys';p.action.route=[];p.needs.expression=50;const before=p.skills.keys;step(practice,10);assert(p.skills.keys>before);assert(p.needs.expression<50);
const learner=quiet().people[0];let gain=0,peaks=0;for(let i=0;i<500;i++){const value=plateauGain(learner,learner.instrument,.02);gain+=value;if(value>=2)peaks++;}assert(peaks>0&&gain>0);
// Group constraints apply to both invitations and collaboration.
const constrained=quiet(),[a,b]=constrained.people;assert(!proposeActivity(constrained,a,b,'practice'));assert(!proposeActivity(constrained,a,b,'write'));
const admissions=quiet(15,3);for(const p of admissions.people){decide(admissions,p,'social');p.action.route=[];p.place='park';p.actionRanges.social={min:150,max:180};for(const q of admissions.people)if(q!==p)Object.assign(relationship(admissions,p,q),{affinity:80,trust:80,tension:0});}step(admissions,40);const exchanges=admissions.events.filter(e=>e.interaction);assert(exchanges.length);assert(exchanges.every(e=>e.rolls.acceptance===null));assert(admissions.events.some(e=>e.admission&&e.accepted));
// Independent draft origins survive alternation, multi-session work and a true V7 migration.
const writing=quiet(14),author=writing.people[0];decide(writing,author,'write');author.action.route=[];step(writing,25);const first=compositionProject(writing,author),work=first.work,source=structuredClone(author.draft);selectProject(writing,author);decide(writing,author,'write',{newProject:true});author.action.route=[];step(writing,20);selectProject(writing,author,first.id);assert.equal(first.work,work);assert.deepEqual(author.draft,source);assert(writing.projects.length>=2);restore(writing);
const legacy=JSON.parse(readFileSync(new URL('v070-world.json',import.meta.url))),migrated=restore(legacy);assert.equal(migrated.version,'0.7.1');assert.deepEqual(migrated.songs,legacy.songs);for(let i=0;i<legacy.people.length;i++){const old=legacy.people[i],next=migrated.people[i];for(const k of Object.keys(old.bag.remaining))assert.equal(next.bag.remaining[k]+next.bag.consumed[k],old.bag.remaining[k]+old.bag.consumed[k]+(old.bag.reserved===k?1:0));assert.deepEqual(next.skills,old.skills);}assert.deepEqual(restore(migrated),migrated);
// Old future edits retire available discard immediately and retain only undrawn pending copies.
const futureEdit=structuredClone(legacy);futureEdit.people[0].bag.composition.practice=0;futureEdit.people[0].waitUntil=futureEdit.time+15;futureEdit.people[0].decadence=65;const futureMigration=restore(futureEdit);assert.equal(futureMigration.people[0].bag.consumed.practice,0);assert.equal(futureMigration.people[0].bag.pendingRemoval.practice,futureEdit.people[0].bag.remaining.practice);assert.equal(futureMigration.people[0].waitUntil,0);assert.equal(futureMigration.people[0].bag.remaining.decadence,3);
// Quality is relative and weak songs remain searchable and reversible.
const catalog=quiet();catalog.songs=[80,85,90,30].map((quality,i)=>({id:i+1,title:'Morceau '+i,authors:[catalog.people[0].id],quality,genre:'Jazz',time:catalog.time,sources:[],intensity:10,tone:'exaltée',emotion:'exaltation',resonance:quality}));classifySongs(catalog);assert(catalog.songs[3].weak);assert.equal(catalogueEntries(catalog,{...DEFAULT_FILTERS,type:'song'}).length,3);assert.equal(catalogueEntries(catalog,{...DEFAULT_FILTERS,status:'weak'}).length,1);assert(command(catalog,{type:'archive',songId:4,restore:true}).ok);classifySongs(catalog);assert(!catalog.songs[3].weak);assert.equal(catalogueEntries(catalog,{...DEFAULT_FILTERS,type:'song',min:80}).length,3);assert(songDetailsHTML(catalog,catalog.songs[0]).includes('Rattachement'));
// Decadence adds immediately and recedes only through discard removal; the stage uses distinct occurrences.
const excess=quiet(),ep=excess.people[0];changeDecadence(excess,ep,100,'test');assert.equal(ep.bag.remaining.decadence,5);assert.equal(activeDeck(ep).length,ep.deck.length+5);changeDecadence(excess,ep,-100,'recovery');assert.equal(ep.bag.remaining.decadence,5);assert.equal(ep.bag.pendingRemoval.decadence,5);assert.equal(activeDeck(ep).length,ep.deck.length);restore(excess);
changeDecadence(excess,ep,100,'test');const band=createGroup(excess,excess.people.map(x=>x.id),{manual:true}),song=catalog.songs[0];const performance=createPerformance({id:'test',seed:141,people:excess.people,group:band,song,opportunity:{id:'test',name:'Test',crowd:10,styles:['Jazz']}});validatePerformance(performance);const twin=structuredClone(performance);advancePerformance(performance,3600);while(twin.status==='playing')advancePerformance(twin,3);assert.deepEqual(performance,twin);validatePerformance(performance);
// Separate banks share one persistent global registry. Projects retain their title when finalized.
const names=quiet();const seen=new Set();for(const kind of ['group','song'])for(let i=0;i<200;i++){const name=musicName(names,kind,()=>.42);assert(!seen.has(normalizeName(name)));seen.add(normalizeName(name));}restore(names);
// A band without a repertoire cannot disguise technique or a jam as a collective rehearsal.
const noPiece=quiet(),emptyBand=createGroup(noPiece,noPiece.people.map(p=>p.id),{manual:true});assert(!proposeActivity(noPiece,...noPiece.people,'practice'));assert(!command(noPiece,{type:'rehearse',groupId:emptyBand.id,actorId:noPiece.people[0].id,songId:null}).ok);
// Two high emotional axes accelerate existing project work; one high axis does not suffice.
const spark=quiet(111),writer=spark.people[0];decide(spark,writer,'write');writer.action.route=[];const calm=structuredClone(spark);writer.emotions.exaltation=100;writer.emotions.distress=100;calm.people[0].emotions.exaltation=100;calm.people[0].emotions.distress=0;step(spark);step(calm);assert(compositionProject(spark,writer).work>compositionProject(calm,calm.people[0]).work*2);
// Exhausting a finite bank refuses a creation without crashing or adding a suffix.
const exhausted=quiet();let generated=0;while(musicName(exhausted,'group',()=>0)){generated++;assert(generated<2000);}assert(generated>200);assert.equal(createGroup(exhausted,exhausted.people.map(p=>p.id),{manual:true}),null);assert(exhausted.events.some(e=>e.text.includes('banque de noms épuisée')));
// Accepted collaboration shares one project, retains both origins and finalizes once.
const collective=quiet(417),[ca,cb]=collective.people;createGroup(collective,[ca.id,cb.id],{manual:true});for(const [x,y] of [[ca,cb],[cb,ca]]){Object.assign(relationship(collective,x,y),{affinity:95,trust:95,tension:0});feel(collective,x,{exaltation:60},log(collective,'system',`Source réelle de ${x.name}`,[x.id]));}
const priorProjects=collective.projects.length;let joined=false;for(let i=0;i<30&&!joined;i++)joined=proposeActivity(collective,ca,cb,'write');assert(joined);assert(collective.projects.length-priorProjects<=1);const shared=compositionProject(collective,ca);assert.equal(cb.draft.projectId,shared.id);for(const x of [ca,cb]){x.action.route=[];x.place=x.action.dest;}step(collective,10);assert(shared.contributions[ca.id]>0&&shared.contributions[cb.id]>0);assert(shared.sources.some(x=>x.text===`Source réelle de ${ca.name}`));assert(shared.sources.some(x=>x.text===`Source réelle de ${cb.name}`));shared.work=shared.target;ca.action.cycleRemaining=1;ca.actionRanges.write={min:1,max:1};step(collective);assert.equal(collective.songs.filter(x=>x.projectId===shared.id).length,1);assert.equal(collective.songs.find(x=>x.projectId===shared.id).authors.length,2);
// Neglected work is preserved as an abandoned project and hidden by default.
const neglected=quiet(525),np=neglected.people[0];decide(neglected,np,'write');const abandoned=compositionProject(neglected,np);decide(neglected,np,'relax');np.action.remaining=100000;neglected.time=abandoned.updated+V71_RULES.abandonMinutes;step(neglected,60);assert.equal(abandoned.status,'abandoned');assert(!catalogueEntries(neglected).some(x=>x.id===abandoned.id));assert(catalogueEntries(neglected,{...DEFAULT_FILTERS,status:'abandoned'}).some(x=>x.id===abandoned.id));
// A current reload reproduces the exact future, including plateaus, bags and drafts.
const running=createWorld(713,8);step(running,1440*7);if(running.performance?.status==='playing'){skipShow(running,true);nextSlot(running);}const resumed=restore(running);step(running,800);step(resumed,800);assert.deepEqual(running,resumed);
for(const mutate of [s=>s.people[0].learningWork.guitar=-1,s=>s.people[0].actionRanges.jam.max=0,s=>s.people[0].bag.pendingRemoval.write=-1,s=>s.people[0].bag.pendingRemoval.jam=99999]){const bad=structuredClone(running);mutate(bad);assert.throws(()=>restore(bad));}
console.log('V7.1 passed: immediate acquisitions, discard-only removal, solo jam, practice, plateaus, admissions, separate projects, real V7 migration, weak catalogue, contaminated decks, uniqueness and exact continuation.');
